### ISSUE TITLE
dart code metrics

### ISSUE THREAD

**Issue by lsaudon** [lsaudon/calm_mind#1]
```yaml
dart_code_metrics:
  metrics:
    cyclomatic-complexity: 20
    # halstead-volume: 150 # Pas pour flutter
    # lines-of-code: 100 # Pas pour flutter
    # maintainability-index: 50
    maximum-nesting-level: 5
    number-of-parameters: 4
    # source-lines-of-code: 50 # Pas pour flutter
    # number-of-methods: 10
    # weight-of-class: 0.33 # Pas pour flutter
  metrics-exclude:    
    - test/**
    - integration_test/**
  rules:
    - avoid-banned-imports
    - avoid-collection-methods-with-unrelated-types
    - avoid-dynamic
    - avoid-global-state
    # - avoid-ignoring-return-values
    # - avoid-late-keyword
    - avoid-missing-enum-constant-in-map
    - avoid-nested-conditional-expressions
    - avoid-non-ascii-symbols
    # - avoid-non-null-assertion
    - avoid-throw-in-catch-block
    - avoid-unnecessary-type-assertions
    - avoid-unnecessary-type-casts
    - avoid-unrelated-type-assertions
    - avoid-unused-parameters
    - ban-name
    - binary-expression-operand-order
    - double-literal-format
    - format-comment
    # - member-ordering
    # - member-ordering-extended
    - newline-before-return
    - no-boolean-literal-compare
    - no-empty-block
    # - no-equal-arguments
    - no-equal-then-else
    # - no-magic-number
    - no-object-declaration
    - prefer-async-await
    - prefer-commenting-analyzer-ignores
    - prefer-conditional-expressions
    # - prefer-correct-identifier-length
    # - prefer-correct-type-name
    - prefer-first
    - prefer-immediate-return
    - prefer-last
    # - prefer-match-file-name
    - prefer-trailing-comma
    - tag-name
    - always-remove-listener
    - avoid-border-all
    - avoid-returning-widgets
    - avoid-unnecessary-setstate
    - avoid-wrapping-in-padding
    - prefer-const-border-radius
    - prefer-extracting-callbacks
    # - prefer-single-widget-per-file
    - prefer-intl-name
    - provide-correct-intl-args
  rules-exclude:
    - test/**
    - integration_test/**
    - test_driver/**
  anti-patterns:
    # - long-method
    - long-parameter-list
```
